### ISSUE TITLE
Bug: Unable to switch to HDMI audio when USB DAC is plugged in

### ISSUE THREAD

**Issue by kevrl** [rtomasa/RePlay-issues#9]
**Describe the bug**
I left my USB DAC plugged in and wanted to switch over to HDMI sound again, but the sound didn't want to change over to HDMI, and was still routing to USB DAC even though the RPI5 was restarted

**To Reproduce**
1. Plug in USB DAC
2. Click on Audio -> USB DAC
3. Try out audio on the DAC and make sure it works
4. Restart device -> Switch back to HDMI audio -> Reboot
5. Audio is still on USB DAC instead of HDMI

**Expected behavior**
The audio should be routed to the selected output

**Setup:**
 - Device: Raspberry Pi 5 2GB
 - OS version: v0.52.0
 - Storage: USB without external power
 - Power adapter: Raspberry Pi 5 official

**Workaround:**  
1. Unplug USB DAC
2. Switch to HDMI Audio
3. Reboot

**Comment by rtomasa** [comment]
Please check if this is now fixed

**Comment by forkymcforkface** [comment]
> Please check if this is now fixed

Problem still exists

- Play game with HDMI audio setting and no usb dac plugged in
- Plug in Ugreen or Apple USB Audio dac and reboot
- No more audio through HDMI even though audio is still set to HDMI
- Unplug USB Dac and reboot
- Audio is back working through HDMI

**Comment by rtomasa** [comment]
Ar you sure that you tested with v.0.54.0? I tested not only with one but two DACs plugged in at the same time, rebooted, changed the options, restarted cores, etc and all worked fine.

**Comment by forkymcforkface** [comment]
> Ar you sure that you tested with v.0.54.0? I tested not only with one but two DACs plugged in at the same time, rebooted, changed the options, restarted cores, etc and all worked fine.

I tried it again in 0.54 and it seems to work now. My previous test was in 0.53. Not sure if it was a testing issues on my side prior. I'm not the owner of this one so I cant close it out.
